import Link from 'next/link'
import { Open_Sans } from 'next/font/google'
import styles from './layout.module.css'

const sans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <header className={styles.header}>
          <h1>Clap devlog</h1>
          <nav className={styles.nav}>
            <Link href="/posts">Posts</Link>
            <Link href="/about">About</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
